server:
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 8081
#    uri-encoding: utf-8
helium:
  config:
    bootxml: ${HELIUM_XML:helium-dev.xml}
    bootpath: src/main/resources/helium;helium;

